store: simresult20190625.h5

base_year: 2014
years: [2014, 2017, 2020]

indicators:
    nonres_sqft:
        dataset: [zones, fazes, cities, growth_centers]

    max_developable_capacity:
        dataset: [cities]
        
dataset_tables:
    DU_and_HH_by_bld_type_by_faz_by_year:
        dataset: [fazes]
