store: simresult20180814.h5

base_year: 2014
years: [2016, 2015, 2014]

indicators:
    number_of_households:
        dataset: [zones, fazes]
        
    number_of_jobs:
        dataset: [zones, fazes]
        
