store: simresult20170404.h5

base_year: 2014
years: [2014, 2015]

indicators:
    number_of_households:
        dataset: [zones, fazes]
        
    number_of_jobs:
        dataset: [zones, fazes]
        
