store: simresult20190205.h5

base_year: 2014A
years: [2014, 2015, 2016]

indicators:
    building_sqft:
        dataset: [zones]
        
dataset_tables:
    DU_and_HH_by_bld_type_by_faz_by_year:
        dataset: [fazes]
    employment_by_aggr_sector:
        dataset: [zones, cities]
    persons_by_5year_age_groups:
        dataset: [alldata]
    persons_by_age_groups_of_interest:
        dataset: [alldata]
    regional_total_hhs_by_30_60_90_in_14dollars_groups:
        dataset: [alldata]
    regional_total_hhs_by_new_14incomegroups:
        dataset: [alldata]