store: simresult20180814.h5

base_year: 2014
years: [2014, 2015, 2016]

indicators:
    number_of_households:
        dataset: [zones, fazes]
        
    number_of_jobs:
        dataset: [zones, fazes]

    building_sqft:
        dataset: [zones, fazes]

    nonres_sqft:
        dataset: [zones, fazes]

    residential_units:
        dataset: [zones, fazes]

    population:
        dataset: [zones, fazes]