store: simresult20190218.h5

base_year: 2014
years: [2040, 2042, 2043, 2048, 2049]

indicators:
    number_of_households:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv
        
    population:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv

    number_of_jobs:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv

    residential_units:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv

    building_sqft:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    nonres_sqft:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    max_developable_capacity:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    max_developable_nonresidential_capacity:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    max_developable_residential_capacity:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

dataset_tables:
    DU_and_HH_by_bld_type_by_faz_by_year:
        dataset: [fazes]
        file_type: tab

    employment_by_aggr_sector:
        dataset: [zones, cities]
        file_type: tab

    persons_by_5year_age_groups:
        dataset: [alldata]
        file_type: csv

    persons_by_age_groups_of_interest:
        dataset: [alldata]
        file_type: csv

    regional_total_hhs_by_30_60_90_in_14dollars_groups:
        dataset: [alldata]
        file_type: csv

    regional_total_hhs_by_new_14incomegroups:
        dataset: [alldata]
        file_type: csv

    pwtyp:
        dataset: [alldata]
        file_type: csv

    pptyp:
        dataset: [alldata]
        file_type: csv

    eoy_vacancy_by_building_type:
        dataset: [counties]
        file_type: csv

    units_and_nonres_sqft_by_building_type:
        dataset: [counties]
        file_type: csv