store: simresult20191209.h5
#store: /Volumes/Model\ Data\ 2/vision2050/opusgit/urbansim_data/data/psrc_parcel/runs/awsmodel07/runUS2_20191125_alloc_stc/results_alloc_stc_20191125.h5
output_directory: run_20191209_alloc_stc

base_year: 2014
years: [2014, 2015, 2016, 2017, 2018, 2019, 2020, 2021, 2022, 2023, 2024, 2025, 2026, 2027, 2028, 2029, 2030, 2031, 2032, 2033, 2034, 2035, 2036, 2037, 2038, 2039, 2040, 2041, 2042, 2043, 2044, 2045, 2046, 2047, 2048, 2049, 2050]

indicators:
    number_of_households:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv
        
    population:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv

    number_of_jobs:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv

    residential_units:
        dataset: [zones, fazes, cities, alldata, growth_centers]
        file_type: csv

    building_sqft:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    nonres_sqft:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    max_developable_capacity:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    max_developable_nonresidential_capacity:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

    max_developable_residential_capacity:
        dataset: [zones, fazes, cities, growth_centers]
        file_type: csv

dataset_tables:
    DU_and_HH_by_bld_type_by_faz_by_year:
        dataset: [fazes]
        file_type: tab

    employment_by_aggr_sector:
        dataset: [zones, cities]
        file_type: tab

    persons_by_5year_age_groups:
        dataset: [alldata]
        file_type: csv

    persons_by_age_groups_of_interest:
        dataset: [alldata]
        file_type: csv

    regional_total_hhs_by_30_60_90_in_14dollars_groups:
        dataset: [alldata]
        file_type: csv

    regional_total_hhs_by_new_14incomegroups:
        dataset: [alldata]
        file_type: csv

    pwtyp:
        dataset: [alldata]
        file_type: csv

    pptyp:
        dataset: [alldata]
        file_type: csv

    eoy_vacancy_by_building_type:
        dataset: [counties]
        file_type: csv

    units_and_nonres_sqft_by_building_type:
        dataset: [counties]
        file_type: csv

   new_buildings:
	dataset: [buildings]
	file_type: tab
	year: [2050]
	include_condition: year_built > 2014
