store: simresult20180814.h5

base_year: 2014
years: [2014, 2015, 2016]

indicators:
    number_of_households:
        dataset: [zones, fazes, cities, alldata]
        
    number_of_jobs:
        dataset: [zones, fazes, cities, alldata]

    building_sqft:
        dataset: [zones, fazes, cities]

    nonres_sqft:
        dataset: [zones, fazes, cities]

    residential_units:
        dataset: [zones, fazes, cities, alldata]

    population:
        dataset: [zones, fazes, cities, alldata]