name: elcm

model_type: segmented_discretechoice

segmentation_col: sector_id

choosers_fit_filters:
- building_id > 0
- sector_id < 18
- for_estimation == 1

choosers_predict_filters: 
- sector_id < 18

alts_fit_filters:
- not building_type_id in [4, 11, 12, 19]

alts_predict_filters:
- not building_type_id in [4, 11, 12, 19]

interaction_predict_filters: null

choice_column: null

sample_size: 30

estimation_sample_size: null

prediction_sample_size: 30

default_config:
    model_expression: np.log1p(median_income)

models:
    mining:
        model_expression: trip_weighted_average_time_hbw_from_home_am_drive_alone
            + is_near_arterial + np.log1p(empden_zone_sector(1, building_zone_id))
            + np.log1p(unit_price_trunc) + np.log1p(median_income) + np.log1p(number_of_jobs_per_acre)
            + np.log1p(population_per_acre) + np.log1p(generalized_cost_hbw_am_drive_alone_to_seattle_cbd)
        name: 1
    construction:
        model_expression: is_near_arterial + np.log1p(empden_zone_sector(2, building_zone_id))
            + np.log1p(number_of_jobs_per_acre) + np.log1p(population_per_acre) +
            np.log1p(generalized_cost_hbw_am_drive_alone_to_seattle_cbd) + is_inside_urban_growth_boundary
            + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone) + np.log1p(building_sqft)
        name: 2
    aerospace:
        fit_parameters:
        model_expression: is_near_arterial + is_near_highway + np.log1p(empden_zone_sector(3,
            building_zone_id)) + np.log1p(generalized_cost_hbw_am_drive_alone_to_seattle_cbd)
            + np.log1p(population_per_acre) + np.log1p(unit_price_trunc) + is_industrial
        name: 3
    other_durable_goods:
        model_expression: is_near_arterial + is_near_highway + np.log1p(empden_zone_sector(4,
            building_zone_id)) + is_inside_urban_growth_boundary + np.log1p(unit_price_trunc)
            + is_industrial + np.log1p(median_income) + np.log1p(number_of_jobs_per_acre)
            + np.log1p(building_sqft) + is_commercial + is_office + is_warehouse
        name: 4
    nondurable_goods:
        model_expression: is_near_arterial + is_near_highway + np.log1p(empden_zone_sector(5,
            building_zone_id)) + is_inside_urban_growth_boundary + np.log1p(unit_price_trunc)
            + np.log1p(median_income) + np.log1p(number_of_jobs_per_acre) + is_commercial
            + is_office + is_warehouse + is_mixed_use + is_industrial + np.log1p(population_per_acre)
            + trip_weighted_average_time_hbw_from_home_am_drive_alone + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(generalized_cost_hbw_am_drive_alone_to_seattle_cbd)
        name: 5
    wholesale:
        model_expression: is_near_arterial +  np.log1p(empden_zone_sector(6, building_zone_id))
            + is_inside_urban_growth_boundary + np.log1p(unit_price_trunc) + np.log1p(number_of_jobs_per_acre)
            + is_commercial + is_office + is_warehouse + is_industrial + np.log1p(population_per_acre)
            + + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone) + np.log1p(generalized_cost_hbw_am_drive_alone_to_bellevue_cbd)
        name: 6
    retail:
        model_expression: is_inside_urban_growth_boundary + is_commercial + is_mixed_use  +
            is_near_arterial + is_near_highway  + is_warehouse + np.log1p(median_income)
            +  np.log1p(number_of_jobs_per_acre)  + np.log1p(generalized_cost_hbw_am_drive_alone_to_seattle_cbd)
            +  np.log1p(empden_zone_sector(7, building_zone_id)) + np.log1p(unit_price_trunc)
        name: 7
    transportation:
        model_expression: is_inside_urban_growth_boundary + is_commercial + is_industrial
            + is_near_arterial + is_near_highway  + is_office  + is_warehouse + np.log1p(median_income)
            + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone) + np.log1p(number_of_jobs_per_acre)  +
            np.log1p(population_per_acre) +  np.log1p(building_sqft) + np.log1p(empden_zone_sector(8,
            building_zone_id))
        name: 8
    utilities:
        model_expression: trip_weighted_average_time_hbw_from_home_am_drive_alone
            +  is_commercial + is_office  + np.log1p(median_income) + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(building_sqft) + np.log1p(unit_price_trunc)
        name: 9
    telecommunication:
        model_expression: is_commercial + is_industrial + is_near_arterial + is_near_highway  +
            is_office  + is_tcu + np.log1p(median_income) + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(number_of_jobs_per_acre)  + np.log1p(generalized_cost_hbw_am_drive_alone_to_bellevue_cbd)
            + +  np.log1p(population_per_acre) +  np.log1p(empden_zone_sector(10,
            building_zone_id)) + np.log1p(unit_price_trunc)
        name: 10
    information:
        model_expression: trip_weighted_average_time_hbw_from_home_am_drive_alone
            + is_inside_urban_growth_boundary + is_commercial + is_industrial + is_mixed_use  +
            is_near_highway  + is_office  + np.log1p(median_income) + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(number_of_jobs_per_acre)  + np.log1p(population_per_acre) +  np.log1p(empden_zone_sector(11,
            building_zone_id)) + np.log1p(unit_price_trunc)
        name: 11
    finance:
        model_expression: trip_weighted_average_time_hbw_from_home_am_drive_alone
            + is_commercial + is_mixed_use  + is_near_highway  + is_office  + np.log1p(median_income)
            + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone) + np.log1p(generalized_cost_hbw_am_drive_alone_to_bellevue_cbd)
            + np.log1p(population_per_acre) + np.log1p(empden_zone_sector(12, building_zone_id))
            + np.log1p(unit_price_trunc)
        name: 12
    professional:
        model_expression: trip_weighted_average_time_hbw_from_home_am_drive_alone
            + is_inside_urban_growth_boundary + is_industrial + is_mixed_use  + is_near_arterial
            + is_near_highway  + is_office  + np.log1p(median_income) + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(number_of_jobs_per_acre)  + np.log1p(population_per_acre) +  np.log1p(empden_zone_sector(13,
            building_zone_id)) + np.log1p(unit_price_trunc)
        name: 13
    food:
        model_expression: is_inside_urban_growth_boundary + is_commercial + is_mixed_use  +
            is_near_arterial + is_office  + np.log1p(median_income) + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(number_of_jobs_per_acre)  + np.log1p(population_per_acre) +  np.log1p(empden_zone_sector(14,
            building_zone_id)) + np.log1p(unit_price_trunc)
        name: 14
    education:
        model_expression: trip_weighted_average_time_hbw_from_home_am_drive_alone
            + is_inside_urban_growth_boundary + is_commercial + is_industrial + is_near_arterial
            + is_near_highway  + np.log1p(median_income) + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(number_of_jobs_per_acre)  + np.log1p(population_per_acre) +
            np.log1p(empden_zone_sector(15, building_zone_id)) + np.log1p(unit_price_trunc)
        name: 15
    health:
        model_expression: trip_weighted_average_time_hbw_from_home_am_drive_alone
            + is_inside_urban_growth_boundary + is_near_arterial + is_office  + np.log1p(median_income)
            + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone) + np.log1p(number_of_jobs_per_acre)  +
            np.log1p(generalized_cost_hbw_am_drive_alone_to_bellevue_cbd) + np.log1p(population_per_acre)
            +  np.log1p(empden_zone_sector(16, building_zone_id)) + np.log1p(unit_price_trunc)
        name: 16
    other_services:
        model_expression: is_commercial + is_industrial + is_mixed_use  + is_near_arterial
            +  is_office  + np.log1p(median_income) + np.log1p(jobs_within_30_min_tt_hbw_am_drive_alone)
            + np.log1p(number_of_jobs_per_acre)  + np.log1p(generalized_cost_hbw_am_drive_alone_to_bellevue_cbd)
            + np.log1p(empden_zone_sector(17, building_zone_id)) + np.log1p(unit_price_trunc)
        name: 17

fitted: false

choice_mode: individual

remove_alts: false

probability_mode: full_product

#choice_mode: aggregate

#remove_alts: true

#probability_mode: single_chooser
