name: Household Location Choice Model

model_type: segmented_discretechoice

segmentation_col: is_inmigrant

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

default_config:
    model_expression: multifamily_type + I((persons < 2)*1):I(np.logical_not(building_type_name
        == "single_family_residential")*1) + I((persons > 3)*1):I(np.logical_not(large_area_id
        == 6)*1) + I((tenure == 1)*1):I(np.logical_not(building_type_name == "multi_family_residential")*1)
        + I((persons-2)*(persons > 2)):I((building_type_name == "condo_residential")*1)
        + I(np.log1p(income)/(persons*persons*1.0)):I(np.log1p(sqft_per_unit)) + I(1*np.logical_or(mortgage_cost/income
        < 0.1, mortgage_cost/income > 0.3)) + ln_price_residual + I((employment_density_wwd
        > 25) * np.log1p(employment_density_wwd)) + I(1*(np.logical_and(persons ==
        1, age_of_head < 50))):I(1*(np.log1p(employment_retail_wwd)>4)) + I(avg_network_distance_from_home_to_work(worker1_zone_id,
        worker2_zone_id, building_zone_id)) + I(max_logsum_hbw_am_from_home_to_work_wzone_logsum(worker1_zone_id,
        worker2_zone_id, building_zone_id, income_category, twa_logsum_hbw_1, twa_logsum_hbw_2,
        twa_logsum_hbw_3, twa_logsum_hbw_4))

models:
    false:
        fit_parameters:
            Coefficient:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.31577138800799254
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -3.0
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 1.2562017533985899
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.36732469033050824
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 1.4634772047655704
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): -3.0
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.34321875127037516
                I(avg_network_distance_from_home_to_work(worker1_zone_id, worker2_zone_id, building_zone_id)): -0.0030512091481433813
                ? I(max_logsum_hbw_am_from_home_to_work_wzone_logsum(worker1_zone_id,
                    worker2_zone_id, building_zone_id, income_category, twa_logsum_hbw_1,
                    twa_logsum_hbw_2, twa_logsum_hbw_3, twa_logsum_hbw_4))
                : 0.04292416298480541
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -0.016429985905436935
                ln_price_residual: 0.03917309482270315
                multifamily_type: 1.7774351600057643
            Std. Error:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.019932711782171847
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): 138.44433357868067
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.07318644938374136
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.051050264002560394
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 0.046855584247928045
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): 189.15146857648043
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.19008293918555275
                I(avg_network_distance_from_home_to_work(worker1_zone_id, worker2_zone_id, building_zone_id)): 0.006304750266588768
                ? I(max_logsum_hbw_am_from_home_to_work_wzone_logsum(worker1_zone_id,
                    worker2_zone_id, building_zone_id, income_category, twa_logsum_hbw_1,
                    twa_logsum_hbw_2, twa_logsum_hbw_3, twa_logsum_hbw_4))
                : 0.044589979106434904
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): 0.0009152464759814777
                ln_price_residual: 0.02939237182807467
                multifamily_type: 0.06020359286794661
            T-Score:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 15.841867953482566
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -0.02166935924679821
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 17.164403574381623
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 7.195353393512035
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 31.233784153065713
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): -0.015860305090821945
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 1.8056262847205673
                I(avg_network_distance_from_home_to_work(worker1_zone_id, worker2_zone_id, building_zone_id)): -0.48395400596798904
                ? I(max_logsum_hbw_am_from_home_to_work_wzone_logsum(worker1_zone_id,
                    worker2_zone_id, building_zone_id, income_category, twa_logsum_hbw_1,
                    twa_logsum_hbw_2, twa_logsum_hbw_3, twa_logsum_hbw_4))
                : 0.9626414688902805
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -17.951433123867538
                ln_price_residual: 1.332763992366422
                multifamily_type: 29.523738955322386
        fitted: true
        log_likelihoods:
            convergence: -12666.754572723503
            'null': -13815.51055796495
            ratio: 0.08314973090727829
        name: false

fitted: true

choice_mode: individual

remove_alts: false

probability_mode: full_product
