name: Household Location Choice Model

model_type: segmented_discretechoice

segmentation_col: is_inmigrant

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

default_config:
    model_expression: multifamily_type + I((persons < 2)*1):I(np.logical_not(building_type_name
        == "single_family_residential")*1) + I((persons > 3)*1):I(np.logical_not(large_area_id
        == 6)*1) + I((tenure == 1)*1):I(np.logical_not(building_type_name == "multi_family_residential")*1)
        + I((persons-2)*(persons > 2)):I((building_type_name == "condo_residential")*1)
        + I(np.log1p(income)/(persons*persons*1.0)):I(np.log1p(sqft_per_unit)) + I(1*np.logical_or(mortgage_cost/income
        < 0.1, mortgage_cost/income > 0.3)) + ln_price_residual
        + I((employment_density_wwd > 25) * np.log(employment_density_wwd-25+1))

models:
    false:
        fit_parameters:
            Coefficient:
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -3.0
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.9933650497529578
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.3483031185415084
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 1.5002583389563022
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.6674529391303087
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -0.018908717794675504
                ln_price_residual: 0.033993606269398534
                multifamily_type: 1.9731378255547685
            Std. Error:
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): 124.95732960292155
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.07215525421457906
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.05169692821013501
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 0.04676613561388291
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.046297631692900416
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): 0.0009045451927550032
                ln_price_residual: 0.029447096019411673
                multifamily_type: 0.05855798208175138
            T-Score:
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -0.024008195513885718
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 13.767050792986424
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 6.737404534477249
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 32.0800151490588
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 14.416567645568366
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -20.904116174764688
                ln_price_residual: 1.1543958781874375
                multifamily_type: 33.695454580386986
        fitted: true
        log_likelihoods:
            convergence: -12732.41525143558
            'null': -13815.51055796495
            ratio: 0.0783970525001656
        name: false

fitted: true

choice_mode: individual

remove_alts: false

probability_mode: full_product
