name: Household Location Choice Model

model_type: segmented_discretechoice

segmentation_col: is_inmigrant

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

default_config:
    model_expression: multifamily_type + I((persons < 2)*1):I(np.logical_not(building_type_name
        == "single_family_residential")*1) + I((persons > 3)*1):I(np.logical_not(large_area_id
        == 6)*1) + I((tenure == 1)*1):I(np.logical_not(building_type_name == "multi_family_residential")*1)
        + I((persons-2)*(persons > 2)):I((building_type_name == "condo_residential")*1)
        + I(np.log1p(income)/(persons*persons*1.0)):I(np.log1p(sqft_per_unit)) + I(1*np.logical_or(mortgage_cost/income
        < 0.1, mortgage_cost/income > 0.3)) + ln_price_residual + I((employment_density_wwd
        > 25) * np.log1p(employment_density_wwd)) + I(1*(np.logical_and(persons ==
        1, age_of_head < 50))):I(1*(np.log1p(employment_retail_wwd)>4)) + I(avg_network_distance_from_home_to_work(worker1_zone_id,
        worker2_zone_id, building_zone_id))

models:
    false:
        fit_parameters:
            Coefficient:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.32081787673967355
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -3.0
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.977660789400265
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.3243004826882885
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 1.483883800455045
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): -3.0
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.7245908396859231
                I(avg_network_distance_from_home_to_work(worker1_zone_id, worker2_zone_id, building_zone_id)): -0.011212732239748365
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -0.017259208832827406
                ln_price_residual: -0.026611243590935814
                multifamily_type: 1.8663342847303868
            Std. Error:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.019552948750054124
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): 128.64856681515963
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.07409656814804175
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.05140523902057956
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 0.04707447101349839
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): 273.21235638366954
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.1886891731153612
                I(avg_network_distance_from_home_to_work(worker1_zone_id, worker2_zone_id, building_zone_id)): 0.0054147260553241575
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): 0.0009071341004285608
                ln_price_residual: 0.028011257497992204
                multifamily_type: 0.05936017164999865
            T-Score:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 16.407646787228728
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -0.0233193425645414
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 13.194413909250708
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 6.30870488820134
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 31.522049393386663
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): -0.010980469696572319
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 3.840129392283261
                I(avg_network_distance_from_home_to_work(worker1_zone_id, worker2_zone_id, building_zone_id)): -2.0707847682752445
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -19.0260831608839
                ln_price_residual: -0.95001959811491
                multifamily_type: 31.440850537541014
        fitted: true
        log_likelihoods:
            convergence: -12646.611385908624
            'null': -13815.51055796495
            ratio: 0.08460774338755295
        name: false

fitted: true

choice_mode: individual

remove_alts: false

probability_mode: full_product
