name: Household Location Choice Model

model_type: segmented_discretechoice

segmentation_col: is_inmigrant

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

default_config:
    model_expression: multifamily_type + I((persons < 2)*1):I(np.logical_not(building_type_name
        == "single_family_residential")*1) + I((persons > 3)*1):I(np.logical_not(large_area_id
        == 6)*1) + I((tenure == 1)*1):I(np.logical_not(building_type_name == "multi_family_residential")*1)
        + I((persons-2)*(persons > 2)):I((building_type_name == "condo_residential")*1)
        + I(np.log1p(income)/(persons*persons*1.0)):I(np.log1p(sqft_per_unit)) + I(1*np.logical_or(mortgage_cost/income
        < 0.1, mortgage_cost/income > 0.3)) + ln_price_residual + I((employment_density_wwd
        > 25) * np.log1p(employment_density_wwd))

models:
    false:
        fit_parameters:
            Coefficient:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.3052220370051016
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -3.0
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 1.0394280593521728
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.3491256494036299
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 1.53186846706584
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.1228412269360746
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -0.01361339073678289
                ln_price_residual: -0.03889379196615377
                multifamily_type: 1.811530713224154
            Std. Error:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.020016861062511205
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): 79.82760712656362
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.07604415698356942
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.051259940595268096
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 0.04693877697313485
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.048128446504741726
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): 0.0009422011632151226
                ln_price_residual: 0.028941927507299497
                multifamily_type: 0.06088797385081802
            T-Score:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 15.24824676815787
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -0.03758098367202232
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 13.66874327473652
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 6.810886734345111
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 32.63545762904296
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 2.552362186133974
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -14.448497060149236
                ln_price_residual: -1.3438563121389997
                multifamily_type: 29.751863933961673
        fitted: true
        log_likelihoods:
            convergence: -12696.893737208691
            'null': -13815.51055796495
            ratio: 0.0809681854364297
        name: false

fitted: true

choice_mode: individual

remove_alts: false

probability_mode: full_product
