name: Household Location Choice Model

model_type: discretechoice

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

model_expression: np.log1p(sqft_per_unit) + np.log1p(avg_income)

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        np.log1p(avg_income): -3.0
        np.log1p(sqft_per_unit): -0.2465721039643284
    Std. Error:
        np.log1p(avg_income): 0.05992448079189128
        np.log1p(sqft_per_unit): 0.020880205464550956
    T-Score:
        np.log1p(avg_income): -50.06301198367574
        np.log1p(sqft_per_unit): -11.808892608022578

probability_mode: single_chooser

log_likelihoods:
    convergence: -13654.700164455518
    'null': -13815.51055796495
    ratio: 0.011639844422305479
