name: Household Location Choice Model

model_type: segmented_discretechoice

segmentation_col: is_inmigrant

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

default_config:
    model_expression: multifamily_type + I((persons < 2)*1):I(np.logical_not(building_type_name
        == "single_family_residential")*1) + I((persons > 3)*1):I(np.logical_not(large_area_id
        == 6)*1) + I((tenure == 1)*1):I(np.logical_not(building_type_name == "multi_family_residential")*1)
        + I((persons-2)*(persons > 2)):I((building_type_name == "condo_residential")*1)
        + I(np.log1p(income)/(persons*persons*1.0)):I(np.log1p(sqft_per_unit)) + np.log1p(avg_income)

models:
    false:
        fit_parameters:
            Coefficient:
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -3.0
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 1.2558798077884405
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.08951133993722467
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 1.67382518082361
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -0.01581061539909715
                multifamily_type: 1.8090876038081396
                np.log1p(avg_income): -2.2712813465393227
            Std. Error:
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): 180.77228192486075
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.07260814784084359
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.052395953434458305
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 0.04678472777526475
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): 0.0009155929374965299
                multifamily_type: 0.05427522323269794
                np.log1p(avg_income): 0.018793750439233016
            T-Score:
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -0.01659546457043105
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 17.2966787493508
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 1.708363605773368
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 35.77717046605468
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -17.268170986909862
                multifamily_type: 33.3317395315338
                np.log1p(avg_income): -120.85301195645839
        fitted: true
        log_likelihoods:
            convergence: -12762.058480411511
            'null': -13815.51055796495
            ratio: 0.07625140403849207
        name: false

fitted: true

choice_mode: individual

remove_alts: false

probability_mode: full_product
