name: Household Location Choice Model

model_type: segmented_discretechoice

segmentation_col: is_inmigrant

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

default_config:
    model_expression: multifamily_type + I((persons < 2)*1):I(np.logical_not(building_type_name
        == "single_family_residential")*1) + I((persons > 3)*1):I(np.logical_not(large_area_id
        == 6)*1) + I((tenure == 1)*1):I(np.logical_not(building_type_name == "multi_family_residential")*1)
        + I((persons-2)*(persons > 2)):I((building_type_name == "condo_residential")*1)
        + I(np.log1p(income)/(persons*persons*1.0)):I(np.log1p(sqft_per_unit)) + I(1*np.logical_or(mortgage_cost/income
        < 0.1, mortgage_cost/income > 0.3)) + ln_price_residual + I((employment_density_wwd
        > 25) * np.log1p(employment_density_wwd)) + I(1*(np.logical_and(persons ==
        1, age_of_head < 50))):I(1*(np.log1p(employment_retail_wwd)>4))

models:
    false:
        fit_parameters:
            Coefficient:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.3092318287502242
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -3.0
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 1.1999034897558294
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.502356978094155
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 1.6280631752114039
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): -3.0
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.18315620762930782
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -0.02131227227900836
                ln_price_residual: 0.007304535867545819
                multifamily_type: 1.9125347302139175
            Std. Error:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 0.01975470695377273
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): 124.32812595124214
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 0.07483604899174882
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 0.0517742271187689
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 0.047665697039562235
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): 148.93889117725675
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 0.047314040579393896
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): 0.0009409196174337761
                ln_price_residual: 0.0278788294568697
                multifamily_type: 0.060249877453628725
            T-Score:
                I((employment_density_wwd > 25) * np.log1p(employment_density_wwd)): 15.653577118296228
                I((persons - 2) * (persons > 2)):I((building_type_name == "condo_residential") * 1): -0.02412969693741312
                I((persons < 2) * 1):I(np.logical_not(building_type_name == "single_family_residential") * 1): 16.03376321868792
                I((persons > 3) * 1):I(np.logical_not(large_area_id == 6) * 1): 9.702838768442831
                I((tenure == 1) * 1):I(np.logical_not(building_type_name == "multi_family_residential") * 1): 34.15586630066736
                I(1 * (np.logical_and(persons == 1, age_of_head < 50))):I(1 * (np.log1p(employment_retail_wwd) > 4)): -0.020142489153015163
                I(1 * np.logical_or(mortgage_cost / income < 0.1, mortgage_cost / income > 0.3)): 3.8710751689441545
                I(np.log1p(income) / (persons * persons * 1.0)):I(np.log1p(sqft_per_unit)): -22.650470756614194
                ln_price_residual: 0.26201013492501163
                multifamily_type: 31.74337958920993
        fitted: true
        log_likelihoods:
            convergence: -12570.142952316723
            'null': -13815.51055796495
            ratio: 0.09014271317901057
        name: false

fitted: true

choice_mode: individual

remove_alts: false

probability_mode: full_product
