name: Household Location Choice Model

model_type: discretechoice

choosers_fit_filters: building_id > 0

choosers_predict_filters: null

alts_fit_filters:
- residential_units > 0

alts_predict_filters:
- vacant_residential_units > 0

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: null

model_expression: np.log1p(sqft_per_unit) + np.log1p(avg_income)

fitted: true

choice_mode: aggregate

fit_parameters:
    Coefficient:
        np.log1p(avg_income): -3.0
        np.log1p(sqft_per_unit): -0.24544318521735017
    Std. Error:
        np.log1p(avg_income): 0.06117127361688435
        np.log1p(sqft_per_unit): 0.021295929285390168
    T-Score:
        np.log1p(avg_income): -49.042627733877154
        np.log1p(sqft_per_unit): -11.525356885258523

probability_mode: single_chooser

log_likelihoods:
    convergence: -13646.711070376932
    'null': -13815.51055796495
    ratio: 0.012218114334594854
