name: repmres

model_type: segmented_regression

segmentation_col: land_use_type_id

fit_filters:
- land_use_type_id in [14, 15, 24]
- total_land_value_per_sqft >= 1
- total_land_value_per_sqft < 1096.63

predict_filters: null

min_segment_size: 10

default_config:
    model_expression: np.log1p(land_value) ~ np.log1p(parcel_sqft) + np.log1p(residential_units)  +
        np.log1p(building_sqft_pcl) + np.log1p(invfar+1)
    ytransform: np.exp

models:
    14:
        fit_parameters:
            Coefficient:
                I(avg_building_age > 60)[T.True]: -0.007732072038697996
                I(blds_with_valid_age == 0)[T.True]: 0.20846403007784692
                I(developable_capacity == 0)[T.True]: -0.2527265344850801
                I(distance_to_arterial < 600)[T.True]: 0.030635583002819038
                ? I(np.log1p(parcel_sqft) * (is_inside_urban_growth_boundary == 0)
                    + I(is_inside_urban_growth_boundary == 0) + np.log1p(developable_capacity)
                    * (developable_capacity > 0))
                : -0.02348622587733395
                Intercept: 7.441721773979425
                is_waterfront: 0.6294526063621823
                np.log1p(avg_building_age): -0.0054126874351838675
                np.log1p(building_density_wwd): 0.45254213176795083
                np.log1p(building_sqft_pcl): -0.06976029926347235
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): -0.7879314539354887
                np.log1p(income_per_person_wwd): 0.31486938143562404
                np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone): -0.03191634246715788
                np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk): -0.040849851614341015
                np.log1p(number_of_jobs_per_acre): 0.0647559347440918
                np.log1p(parcel_sqft): 0.4261611311443876
                np.log1p(park_area_wwd): -0.0016709191403954317
                np.log1p(residential_units): 0.47097632418076274
                np.log1p(retail_density_wwd): 0.03341411770369773
                np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone): 0.2714164380762555
                number_of_good_public_schools_within_3000_radius: 0.04026141059507829
            Std. Error:
                I(avg_building_age > 60)[T.True]: 0.007762508392364491
                I(blds_with_valid_age == 0)[T.True]: 0.04861744900654166
                I(developable_capacity == 0)[T.True]: 0.04385421326891367
                I(distance_to_arterial < 600)[T.True]: 0.0057545657042130235
                ? I(np.log1p(parcel_sqft) * (is_inside_urban_growth_boundary == 0)
                    + I(is_inside_urban_growth_boundary == 0) + np.log1p(developable_capacity)
                    * (developable_capacity > 0))
                : 0.0013403044784069792
                Intercept: 0.17534793602461216
                is_waterfront: 0.02525995259702855
                np.log1p(avg_building_age): 0.005134256898078438
                np.log1p(building_density_wwd): 0.027307117880584618
                np.log1p(building_sqft_pcl): 0.004084421687361031
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): 0.0074207828764277966
                np.log1p(income_per_person_wwd): 0.008353529311704086
                np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone): 0.004749306574887202
                np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk): 0.002350779268906459
                np.log1p(number_of_jobs_per_acre): 0.0044471036900579075
                np.log1p(parcel_sqft): 0.00419299171593786
                np.log1p(park_area_wwd): 0.0005541301144202931
                np.log1p(residential_units): 0.005774558481796516
                np.log1p(retail_density_wwd): 0.006463890034305479
                np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone): 0.019182044576120893
                number_of_good_public_schools_within_3000_radius: 0.001131635999804315
            T-Score:
                I(avg_building_age > 60)[T.True]: -0.9960790569068584
                I(blds_with_valid_age == 0)[T.True]: 4.287843857249633
                I(developable_capacity == 0)[T.True]: -5.762879222923533
                I(distance_to_arterial < 600)[T.True]: 5.32370027166258
                ? I(np.log1p(parcel_sqft) * (is_inside_urban_growth_boundary == 0)
                    + I(is_inside_urban_growth_boundary == 0) + np.log1p(developable_capacity)
                    * (developable_capacity > 0))
                : -17.523052601636113
                Intercept: 42.43974547230993
                is_waterfront: 24.91899396660894
                np.log1p(avg_building_age): -1.054229958226211
                np.log1p(building_density_wwd): 16.57231399325773
                np.log1p(building_sqft_pcl): -17.079602598169753
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): -106.17902006516888
                np.log1p(income_per_person_wwd): 37.69297618845512
                np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone): -6.720211037948399
                np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk): -17.377153250693606
                np.log1p(number_of_jobs_per_acre): 14.561372807398739
                np.log1p(parcel_sqft): 101.63653067200651
                np.log1p(park_area_wwd): -3.0153913258142895
                np.log1p(residential_units): 81.56057743036969
                np.log1p(retail_density_wwd): 5.169351199720395
                np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone): 14.14950512700471
                number_of_good_public_schools_within_3000_radius: 35.5780574336981
        fit_rsquared: 0.8329386442402518
        fit_rsquared_adj: 0.8328385115647784
        fitted: true
        model_expression: np.log1p(land_value) ~ np.log1p(retail_density_wwd) + np.log1p(park_area_wwd)
            + np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk) + np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone)
            + np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd) + np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone)
            + I(avg_building_age > 60) + I(blds_with_valid_age == 0) + np.log1p(avg_building_age)
            + np.log1p(building_sqft_pcl) + np.log1p(building_density_wwd) + np.log1p(parcel_sqft)
            + number_of_good_public_schools_within_3000_radius + I(distance_to_arterial
            < 600) + np.log1p(residential_units) + np.log1p(number_of_jobs_per_acre)
            + np.log1p(income_per_person_wwd) + I(np.log1p(parcel_sqft)*(is_inside_urban_growth_boundary
            == 0) + I(is_inside_urban_growth_boundary == 0) + np.log1p(developable_capacity)
            * (developable_capacity > 0)) + I(developable_capacity == 0) + is_waterfront
        name: 14
    15:
        fit_parameters:
            Coefficient:
                I(number_of_good_public_schools_within_3000_radius == 0)[T.True]: 0.5615384940930463
                I(total_improvement_value <= 0)[T.True]: 1.3364126936381004
                Intercept: 0.17890910804617466
                developable_capacity > 0[T.True]: -0.772356819100143
                is_waterfront: 0.7626595634408437
                np.log1p(building_sqft_pcl): 0.14773156218714764
                np.log1p(developable_capacity): 0.1572668603856771
                np.log1p(developable_capacity):developable_capacity > 0[T.True]: 0.15726686038568055
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): -1.696002521743867
                np.log1p(income_per_person_wwd): -0.6586434234055685
                np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone): 0.7195144612870377
                np.log1p(number_of_jobs_per_acre): 0.3274426745351343
                np.log1p(parcel_sqft): 0.21246143463990885
                np.log1p(park_area_wwd): -0.02744963137108928
                np.log1p(population_per_acre): -0.42948188586761327
                np.log1p(residential_units): 0.18796337180635875
                np.log1p(total_improvement_value): -0.11864125515204871
                np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone): 4.800029892168209
                number_of_good_public_schools_within_3000_radius: 0.021411420429055233
            Std. Error:
                I(number_of_good_public_schools_within_3000_radius == 0)[T.True]: 0.06146270859157614
                I(total_improvement_value <= 0)[T.True]: 0.5455205374080851
                Intercept: 1.2226923469690347
                developable_capacity > 0[T.True]: 0.5193899546823442
                is_waterfront: 0.10793166103854249
                np.log1p(building_sqft_pcl): 0.02681353548557908
                np.log1p(developable_capacity): 0.16827407582942944
                np.log1p(developable_capacity):developable_capacity > 0[T.True]: 0.16827407582942983
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): 0.060608579216144286
                np.log1p(income_per_person_wwd): 0.08698184247468678
                np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone): 0.03559105849009606
                np.log1p(number_of_jobs_per_acre): 0.0267573061314458
                np.log1p(parcel_sqft): 0.026481959271822637
                np.log1p(park_area_wwd): 0.003634289284681412
                np.log1p(population_per_acre): 0.03771877073512514
                np.log1p(residential_units): 0.04372586743858745
                np.log1p(total_improvement_value): 0.03185658182653377
                np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone): 0.1613294764741659
                number_of_good_public_schools_within_3000_radius: 0.00797324943096711
            T-Score:
                I(number_of_good_public_schools_within_3000_radius == 0)[T.True]: 9.136247115702428
                I(total_improvement_value <= 0)[T.True]: 2.4497935494560052
                Intercept: 0.14632389618670413
                developable_capacity > 0[T.True]: -1.4870461242796116
                is_waterfront: 7.0661338489778025
                np.log1p(building_sqft_pcl): 5.509589075510053
                np.log1p(developable_capacity): 0.9345875745298416
                np.log1p(developable_capacity):developable_capacity > 0[T.True]: 0.93458757452986
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): -27.982878722425216
                np.log1p(income_per_person_wwd): -7.572194433536461
                np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone): 20.216157984940438
                np.log1p(number_of_jobs_per_acre): 12.23750526030407
                np.log1p(parcel_sqft): 8.022874458007808
                np.log1p(park_area_wwd): -7.552957186647172
                np.log1p(population_per_acre): -11.386423191879462
                np.log1p(residential_units): 4.298676797443789
                np.log1p(total_improvement_value): -3.7242305467070183
                np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone): 29.75296267658099
                number_of_good_public_schools_within_3000_radius: 2.685407074548043
        fit_rsquared: 0.6588331652073769
        fit_rsquared_adj: 0.6577043531810097
        fitted: true
        model_expression: np.log1p(land_value) ~ np.log1p(population_per_acre) + np.log1p(park_area_wwd)
            + np.log1p(jobs_within_20_min_tt_hbw_am_drive_alone) + np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd)
            + np.log1p(trip_weighted_average_time_hbw_from_home_am_drive_alone) +
            np.log1p(residential_units) + np.log1p(building_sqft_pcl) + np.log1p(parcel_sqft)
            + I(number_of_good_public_schools_within_3000_radius == 0) + number_of_good_public_schools_within_3000_radius
            + np.log1p(income_per_person_wwd) + np.log1p(number_of_jobs_per_acre)
            + np.log1p(total_improvement_value) + I(total_improvement_value <= 0)
            + np.log1p(developable_capacity) * (developable_capacity > 0) + is_waterfront
        name: 15
    24:
        fit_parameters:
            Coefficient:
                I(avg_building_age < 10)[T.True]: -0.024830200276698276
                I(avg_building_age > 60)[T.True]: 0.02851938168115247
                I(blds_with_valid_age == 0)[T.True]: -0.26600664602625557
                I(distance_to_arterial < 600)[T.True]: -0.04866296082693701
                I(distance_to_highway < 200)[T.True]: -0.07919952885299626
                I(is_inside_urban_growth_boundary == 0)[T.True]: -0.009157968726345056
                I(np.log1p(parcel_sqft) * (is_inside_urban_growth_boundary == 0)): -0.007403645999662615
                I(number_of_good_public_schools_within_3000_radius == 0)[T.True]: -0.10971234171108593
                I(total_improvement_value <= 0)[T.True]: 1.7758972674823448
                Intercept: 6.270300630044737
                avg_building_age: 0.000598910625310186
                avg_school_score: 0.04202029124187055
                is_waterfront: 0.9742794951819371
                np.log1p(building_density_wwd): 0.737039900934628
                np.log1p(building_sqft_pcl): 0.03781478462652733
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): -0.8379488587184518
                np.log1p(generalized_cost_weighted_access_to_employment_hbw_am_drive_alone): -0.3519868610074162
                np.log1p(generalized_cost_weighted_access_to_population_hbw_am_drive_alone): 0.24206336382385563
                np.log1p(jobs_within_10_min_tt_hbw_am_drive_alone): 0.013017831228667544
                np.log1p(jobs_within_10_min_tt_hbw_am_walk): 0.00281382760240233
                np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk): -0.024632599376288346
                np.log1p(median_income): 0.46188355958881
                np.log1p(parcel_sqft): 0.23182345501870624
                np.log1p(park_area_wwd): 0.007268665964262058
                np.log1p(retail_density_wwd): 0.0382266528204723
                np.log1p(total_improvement_value): 0.11302300671677545
            Std. Error:
                I(avg_building_age < 10)[T.True]: 0.0014371330080393263
                I(avg_building_age > 60)[T.True]: 0.0015005706387949107
                I(blds_with_valid_age == 0)[T.True]: 0.011056897502882034
                I(distance_to_arterial < 600)[T.True]: 0.0008053848256051089
                I(distance_to_highway < 200)[T.True]: 0.004060002491778991
                I(is_inside_urban_growth_boundary == 0)[T.True]: 0.010719131684312428
                I(np.log1p(parcel_sqft) * (is_inside_urban_growth_boundary == 0)): 0.0010605560502905092
                I(number_of_good_public_schools_within_3000_radius == 0)[T.True]: 0.0010274294635403513
                I(total_improvement_value <= 0)[T.True]: 0.01221740630080135
                Intercept: 0.02685472531528247
                avg_building_age: 2.7520951091792183e-05
                avg_school_score: 0.00031345580485810543
                is_waterfront: 0.002760981823506836
                np.log1p(building_density_wwd): 0.006896223180052114
                np.log1p(building_sqft_pcl): 0.0011605395676710845
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): 0.0018362185056184262
                np.log1p(generalized_cost_weighted_access_to_employment_hbw_am_drive_alone): 0.0039435066955856345
                np.log1p(generalized_cost_weighted_access_to_population_hbw_am_drive_alone): 0.0033749631068903077
                np.log1p(jobs_within_10_min_tt_hbw_am_drive_alone): 0.00031611906622591095
                np.log1p(jobs_within_10_min_tt_hbw_am_walk): 0.00017828898433798707
                np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk): 0.00034050812269896785
                np.log1p(median_income): 0.0014675880189835497
                np.log1p(parcel_sqft): 0.000711340886319261
                np.log1p(park_area_wwd): 7.126431853324923e-05
                np.log1p(retail_density_wwd): 0.0012738369077146918
                np.log1p(total_improvement_value): 0.0009281309849371108
            T-Score:
                I(avg_building_age < 10)[T.True]: -17.277593749359358
                I(avg_building_age > 60)[T.True]: 19.005690864414102
                I(blds_with_valid_age == 0)[T.True]: -24.057982445520512
                I(distance_to_arterial < 600)[T.True]: -60.42199862702295
                I(distance_to_highway < 200)[T.True]: -19.507261144141076
                I(is_inside_urban_growth_boundary == 0)[T.True]: -0.8543573300576061
                I(np.log1p(parcel_sqft) * (is_inside_urban_growth_boundary == 0)): -6.9809096818924345
                I(number_of_good_public_schools_within_3000_radius == 0)[T.True]: -106.78333219395462
                I(total_improvement_value <= 0)[T.True]: 145.35796090908937
                Intercept: 233.4896580184508
                avg_building_age: 21.76198865048688
                avg_school_score: 134.05491488949204
                is_waterfront: 352.87428801123536
                np.log1p(building_density_wwd): 106.87587708393427
                np.log1p(building_sqft_pcl): 32.58379608927271
                np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd): -456.34485011152645
                np.log1p(generalized_cost_weighted_access_to_employment_hbw_am_drive_alone): -89.25732556798513
                np.log1p(generalized_cost_weighted_access_to_population_hbw_am_drive_alone): 71.7232621979364
                np.log1p(jobs_within_10_min_tt_hbw_am_drive_alone): 41.18015209928684
                np.log1p(jobs_within_10_min_tt_hbw_am_walk): 15.782397397407816
                np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk): -72.34071005720244
                np.log1p(median_income): 314.72290153248196
                np.log1p(parcel_sqft): 325.8964295139085
                np.log1p(park_area_wwd): 101.99586713048794
                np.log1p(retail_density_wwd): 30.009063632056524
                np.log1p(total_improvement_value): 121.77484487756195
        fit_rsquared: 0.7793066016920981
        fit_rsquared_adj: 0.7793003854949611
        fitted: true
        model_expression: np.log1p(land_value) ~ np.log1p(retail_density_wwd) + np.log1p(park_area_wwd)
            + np.log1p(median_income) + np.log1p(jobs_within_10_min_tt_hbw_am_walk)
            + np.log1p(jobs_within_20_min_tt_hbw_am_transit_walk) + np.log1p(jobs_within_10_min_tt_hbw_am_drive_alone)
            + np.log1p(generalized_cost_hbw_am_drive_alone_to_cbd) + I(distance_to_arterial
            < 600) + I(distance_to_highway < 200) + I(avg_building_age > 60) + I(avg_building_age
            < 10) + avg_building_age + I(blds_with_valid_age == 0) + np.log1p(parcel_sqft)
            + np.log1p(building_sqft_pcl) + I(np.log1p(parcel_sqft)*(is_inside_urban_growth_boundary
            == 0)) + I(is_inside_urban_growth_boundary == 0) + I(number_of_good_public_schools_within_3000_radius
            == 0) + np.log1p(building_density_wwd) + np.log1p(total_improvement_value)
            + I(total_improvement_value <= 0) + avg_school_score + np.log1p(generalized_cost_weighted_access_to_population_hbw_am_drive_alone)
            + np.log1p(generalized_cost_weighted_access_to_employment_hbw_am_drive_alone)
            + is_waterfront
        name: 24

fitted: true
