#store: psrc_base_year_devtest_2014.h5
#store: psrc_estimation_2014.h5
store: psrc_base_year_2014.h5

base_year: 2014

households_transition:
  total_column: total_number_of_households

jobs_transition:
  total_column: total_number_of_jobs
  
  
cell_walking_radius: 600

cell_size: 150

income_breaks: [34000, 64000, 102000]

near_arterial_threshold: 300

abs_min_year_built: 1800

percent_of_max_profit: .65