#store: psrc_base_year_devtest_2014.h5
#store: psrc_estimation_2014.h5
store: psrc_base_year_2014.h5
#store: psrc_base_year_2014_buildings_prior_2005.h5

base_year: 2014

households_transition:
  total_column: total_number_of_households
  remove_columns: city_id

jobs_transition:
  total_column: total_number_of_jobs
  remove_columns: city_id
  
real_estate_price_model:
  ytransform_back: np.expm1
  ytransform_out: np.log1p
  
feasibility_model:
  development_filter: capacity_opportunity_non_gov
  config_file: proforma.yaml
  
cell_walking_radius: 600

cell_size: 150

income_breaks: [34000, 64000, 102000]

near_arterial_threshold: 300

abs_min_year_built: 1800
