store: psrc_base_year_2014.h5

households_transition:
  total_column: total_number_of_households

jobs_transition:
  total_column: total_number_of_jobs
  

cell_walking_radius: 600

cell_size: 150

income_breaks: [34000, 64000, 102000]

near_arterial_threshold: 300