name: Work-At-Home Choice Model

model_type: discretechoice

choosers_fit_filters: job_id > 0

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: 100

model_expression: age + edu +
    I(1*(employment_status == 2)) 

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        age: -0.0195561
        edu: -0.0811701
        I(1*(employment_status == 2)): -0.896509
    Std. Error:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 1.133425700359179
        I(1 * (household_district_id == district_id)): 0.19708570539815012
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): 0.040695621192765964
        I(np.where(is_in_sector_group_edu, edu * 1, 0)): 0.06354411529015397
        I(np.where(is_in_sector_group_retail, edu * 1, 0)): 0.04103839519620993
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): 0.016523785318818592
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 0.1875292166974972
        network_distance_from_home_to_work(workplace_zone_id, zone_id): 0.10291759846378688
    T-Score:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 2.489013289391466
        I(1 * (household_district_id == district_id)): 1.9918199490714819
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): -1.8612977014204235
        I(np.where(is_in_sector_group_edu, edu * 1, 0)): 0.7327224611091948
        I(np.where(is_in_sector_group_retail, edu * 1, 0)): -1.9616716229194073
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): -15.12378731138525
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 15.997507230242906
        network_distance_from_home_to_work(workplace_zone_id, zone_id): -29.14953365391241

probability_mode: full_product

log_likelihoods:
    convergence: -288.3007301476884
    'null': -9905.721070060497
    ratio: 0.9708955331864672
