name: Workplace Location Choice Model

model_type: discretechoice

choosers_fit_filters: job_id > 0

choosers_predict_filters: null

alts_fit_filters:

alts_predict_filters:

interaction_predict_filters: null

choice_column: 

sample_size: 100 # #alternatives in estimation

estimation_sample_size: 3000 # #choosers in estimation

prediction_sample_size: 100 # #alternatives in prediction 

model_expression: logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id, 
                                                                    household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2,
                                                                    twa_logsum_hbw_3, twa_logsum_hbw_4) +
            generalized_cost_from_home_to_work(workplace_zone_id, zone_id) +                                                        
            I(1*(household_district_id == district_id)) +
            I((household_district_id==19)*1):I((district_id ==19)*1) +
            network_distance_from_home_to_work(workplace_zone_id, zone_id) +
            I(np.where(is_in_sector_group_basic, edu * 1, 0)) 
            