name: Workplace Location Choice Model

model_type: discretechoice

choosers_fit_filters: job_id > 0

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: 100

model_expression: logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id,
    zone_id, household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
    twa_logsum_hbw_4) + generalized_cost_from_home_to_work(workplace_zone_id, zone_id)
    + I(1*(household_district_id == district_id)) + I((household_district_id==19)*1):I((district_id
    ==19)*1) + network_distance_from_home_to_work(workplace_zone_id, zone_id) + I(np.where(is_in_sector_group_basic,
    edu * 1, 0))

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 2.9715950245989124
        I(1 * (household_district_id == district_id)): 0.05883493506957177
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): 0.008321798009157791
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): -0.807942016128539
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 3.0
        network_distance_from_home_to_work(workplace_zone_id, zone_id): -3.0
    Std. Error:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 1.1718719039113532
        I(1 * (household_district_id == district_id)): 0.15248795752262345
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): 0.033698247541047145
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): 0.014536475282953824
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 0.12391105011679611
        network_distance_from_home_to_work(workplace_zone_id, zone_id): 0.23896399280016337
    T-Score:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 2.53576778714519
        I(1 * (household_district_id == district_id)): 0.3858333210400755
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): 0.24695046824085376
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): -55.580324693701435
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 24.210915791386316
        network_distance_from_home_to_work(workplace_zone_id, zone_id): -12.554192641519794

probability_mode: full_product

log_likelihoods:
    convergence: -445.6023670647577
    'null': -9905.721070060497
    ratio: 0.955015655709147
