name: Workplace Location Choice Model

model_type: discretechoice

choosers_fit_filters: job_id > 0

choosers_predict_filters: null

alts_fit_filters: null

alts_predict_filters: null

interaction_predict_filters: null

choice_column: null

sample_size: 100

estimation_sample_size: 3000

prediction_sample_size: 100

model_expression: logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id,
    zone_id, household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
    twa_logsum_hbw_4) + generalized_cost_from_home_to_work(workplace_zone_id, zone_id)
    + I(1*(household_district_id == district_id)) + I((household_district_id==19)*1):I((district_id
    ==19)*1) + network_distance_from_home_to_work(workplace_zone_id, zone_id) + I(np.where(is_in_sector_group_basic,
    edu * 1, 0))

fitted: true

choice_mode: individual

fit_parameters:
    Coefficient:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 1.3991445029818042
        I(1 * (household_district_id == district_id)): 0.22297192005930172
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): 0.008706865444818305
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): -0.7082851543287596
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 3.0
        network_distance_from_home_to_work(workplace_zone_id, zone_id): -3.0
    Std. Error:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 0.828747677882187
        I(1 * (household_district_id == district_id)): 0.14813643723762296
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): 0.03416603492337796
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): 0.01377897753796862
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 0.11656030282424222
        network_distance_from_home_to_work(workplace_zone_id, zone_id): 0.12573917431877904
    T-Score:
        I((household_district_id == 19) * 1):I((district_id == 19) * 1): 1.6882635575610068
        I(1 * (household_district_id == district_id)): 1.5051794427972947
        I(np.where(is_in_sector_group_basic, edu * 1, 0)): 0.2548397981897709
        generalized_cost_from_home_to_work(workplace_zone_id, zone_id): -51.40331729092718
        ? logsum_hbw_am_from_home_to_work_wzone_logsum(workplace_zone_id, zone_id,
            household_income_category, twa_logsum_hbw_1, twa_logsum_hbw_2, twa_logsum_hbw_3,
            twa_logsum_hbw_4)
        : 25.73775056610491
        network_distance_from_home_to_work(workplace_zone_id, zone_id): -23.858912834867823

probability_mode: full_product

log_likelihoods:
    convergence: -473.5028844922137
    'null': -9905.721070060497
    ratio: 0.9521990493025944
